In [25]:
import numpy as np
from enum import Enum

In [19]:
grid = np.zeros((10,5), dtype=int)

In [27]:
# probability to have a cell with no fuel
p_nofuel = 0.2

for i in range(len(grid)):
            for j in range(len(grid[i])):
                # Change how the grid is populated
                grid[i][j] = np.random.choice(3,1,p=[0,p_nofuel,1-p_nofuel])
               

In [28]:
print(grid)

[[1 2 2 2 1]
 [2 2 1 2 2]
 [1 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 1 2 2]
 [2 1 2 2 1]
 [2 2 2 2 2]
 [1 1 2 2 2]]
